#PBS -S /bin/bash
#PBS -N run_partition_test 
#PBS -q devel
#PBS -l select=10:ncpus=28:model=bro
#PBS -l walltime=1:20:00
#PBS -j oe
#PBS -W group_list=e1305
cd $PBS_O_WORKDIR
export MPI_SHEPHERD=true

#F_UFMTENDIAN=big
#export F_UFMTENDIAN

#FORT_BUFFERED=0
#export FORT_BUFFERED

OMP_NUM_THREADS=1
export OMP_NUM_THREADS

make
mpiexec -np 28 ../bin/gradientReconstruction_test > gradientReconstruction_test.log
